version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging to Amazon ECR
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=024615928572.dkr.ecr.us-east-2.amazonaws.com/jayregistry
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $REPOSITORY_URI
      - echo $COMMIT_HASH
      - echo $IMAGE_TAG
  build:
    commands:
      - echo Build started on 'date'
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build components on 'date'
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo writing image to defined file
      - printf '[{"name":"jay-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinations.json
      - cat imagedefinations.json
artifacts:
    files: imagedefinations.json
